version: "3.3"

services:

  # Telegraf to collect server metrics and dump into InfluxDB
  telegraf:
    container_name: telegraf
    image: telegraf
    restart: unless-stopped
    networks:
      - traefik_proxy
    volumes:
      - ${DOCKER_LOCATION}/telegraf:/etc/telegraf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc:/host/proc:ro
    environment:
      - HOST_PROC=/host/proc
      - TZ
      - PUID
      - PGID

  # InfluxDB for time-series data collection
  influxdb:
    container_name: influxdb
    image: influxdb:latest
    restart: unless-stopped
    networks:
      - traefik_proxy
    volumes:
      - ${DOCKER_LOCATION}/influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=InfluxDB()1
      - TZ
      - PUID
      - PGID
    labels:
        - traefik.enable=true
        - traefik.http.routers.influxdb.rule=Host(`influxdb.${DOMAINNAME}`)
        - traefik.http.routers.influxdb.entrypoints=websecure
        - traefik.http.routers.influxdb.tls=true
        - traefik.http.routers.influxdb.tls.certresolver=letsencrypt
        - traefik.http.services.influxdb.loadbalancer.server.port=8086

  # Grafana to create dashboards from data in InfluxDB
  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: unless-stopped
    networks:
      - traefik_proxy
    volumes:
     - ${DOCKER_LOCATION}/grafana:/var/lib/grafana
    environment:
     - GF_SECURITY_ADMIN_PASSWORD=Gr4f4n4()
     # Comment out if you have users that should sign up
     - GF_USERS_ALLOW_SIGN_UP=false
     - GF_SERVER_ROOT_URL=https://grafana.srv.brooks.haus
     - TZ
     - PUID
     - PGID
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`grafana.${DOMAINNAME}`)
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.tls=true
      - traefik.http.routers.grafana.tls.certresolver=letsencrypt
      - traefik.http.services.grafana.loadbalancer.server.port=3000
